name: Test Smart Contracts with Hardhat on Multiple Node Versions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18, 20]  # Specify the Node.js versions to test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}  # Use matrix version

      - name: Install dependencies
        run: |
          npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run tests with Hardhat
        run: npx hardhat test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: hardhat-test-results
          path: ./test-results
